### ISSUE TITLE
Rounded borders do not work

### ISSUE THREAD

**Issue by TheFineBroccoli** [ibhagwan/picom#10]
### Platform

Arch Linux x86_64

### GPU, drivers, and screen setup

Intel HD Graphics (Iron Lake)

`glxinfo -B`:
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) HD Graphics (ILK) (0x46)
    Version: 20.1.6
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics (ILK)
OpenGL version string: 2.1 Mesa 20.1.6
OpenGL shading language version string: 1.20

OpenGL ES profile version string: OpenGL ES 2.0 Mesa 20.1.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
```
 
### Environment
SpectrWM

### picom version

**Version:** vgit-44b49

#### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

#### Drivers (inaccurate):

Intel

### Configuration:

```
# Backend
backend = "glx";
vsync = true;
mark-wmwin-focused = true;
unredir-if-possible = true;
detect-rounded-corners = true;

# Rounded corners
corner-radius = 16.0;
round-borders = 1;

# Shadow
shadow = false;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.60;

# Fade
fading = false;
fade-delta = 3.0;
fade-in-step = 0.03;
fade-out-step = 0.028;

opacity-rule = [
    "0:_NET_WM_STATE@:32a * = '_NET_WM_STATE_HIDDEN'"
];

wintypes:
{
    tooltip = { fade = false; shadow = false; focus = true; };
};

```

### Steps of reproduction

Enabling rounded corners and borders

i.e.: 
```
corner-radius = 16.0;
round-borders = 1;
```

### Expected behavior

Borders are rounded and not cut off by rounded corners

### Current Behavior

Borders are cut of by rounded corners

### Other details

Starting picom from command line shows this error:

```
[ 09/02/2020 19:21:05.858 glx_init_rounded-corners ERROR ] GLX error at line 1124: GL_INVALID_ENUM
```

**Comment by ibhagwan** [comment]
Perhaps the issue stems from your config file? Can you post your `picom.conf`?

What happens if you use the provided  [`picom.conf` sample file](https://github.com/ibhagwan/picom/blob/next/picom.sample.conf)?

**Comment by Urimu** [comment]
The default work but only on my terminal (urxvt) nautilus and firefox still have cut off corners (I deleted the window exclusions)

Here is my config which didn't work:
```
# Backend
backend = "glx";
vsync = true;
mark-wmwin-focused = true;
unredir-if-possible = true;
detect-rounded-corners = true;

# Rounded corners
corner-radius = 16.0;
round-borders = 1;

# Shadow
shadow = false;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.60;

# Fade
fading = false;
fade-delta = 3.0;
fade-in-step = 0.03;
fade-out-step = 0.028;

opacity-rule = [
    "0:_NET_WM_STATE@:32a * = '_NET_WM_STATE_HIDDEN'"
];

wintypes:
{
    tooltip = { fade = false; shadow = false; focus = true; };
};
```

**Comment by ibhagwan** [comment]
I’m not next to my computer ATM, but if it works with the default config and not with your posted one then it’s a configuration issue, just comment out lines by placing `#` at the start of the line until you figure out the offending line.

**Comment by Urimu** [comment]
Ok, found the problem, I had to add:

```
round-borders-rule = [
  "2:class_g      = 'URxvt'",
  "2:class_g      = 'firefox'",
];
```
But there are still some issues (these happen on any window, with no apparent reason, but they are more likely to appear on the first one opened):

![Notice the corners on the terminal window](https://user-images.githubusercontent.com/46381898/92029030-397a0800-ed65-11ea-91a3-4d137e50f880.png)

![Corners still cut of the border](https://user-images.githubusercontent.com/46381898/92029099-56164000-ed65-11ea-9b3b-56182412d91a.png)

**Comment by ibhagwan** [comment]
Can you try adding `experimental-backends = true;` to your config file?

**Comment by Urimu** [comment]
Sorry for the late reply. I get a `glx_init ERROR - Failed to get GLX context` with `experimental-backends = true;`

**Comment by ibhagwan** [comment]
I'm not sure why this would happen, can you try using the provided [sample config](https://github.com/ibhagwan/picom/blob/next/picom.sample.conf) with no changes (it already contains `experimental-backends = true;`)?

If that works, you can try modifying the sample config until you find out which option causes the GLX init issue.

**Comment by Urimu** [comment]
Again sorry for the late reply, this happens with the default config:

![2020-09-07--00:54:01](https://user-images.githubusercontent.com/46381898/92336737-11134600-f0a4-11ea-8def-c0514dcc55e3.png)

Also I should mention that my gpu supports only OpenGL 2.*

**Comment by ibhagwan** [comment]
> Again sorry for the late reply, this happens with the default config:
> 
> ![2020-09-07--00:54:01](https://user-images.githubusercontent.com/46381898/92336737-11134600-f0a4-11ea-8def-c0514dcc55e3.png)
> 
> Also I should mention that my gpu supports only OpenGL 2.*

I would assume this is related to your GPU indeed, you can try`xrender` backend which doesn’t require the GPU. You can also try to play with different blur methods (I.e. not dual kawase) as perhaps the unit function for the blur fails.

**Comment by Urimu** [comment]
`xrender` is even worse, but no error message(!)

![2020-09-07--20:43:21](https://user-images.githubusercontent.com/46381898/92412065-b54fc800-f14a-11ea-97ec-70e340b8097e.png)

It had simmilar results without blur, it just wasn't blury

**Comment by kdkasad** [comment]
I also have these issues, but only when `experimental-backends` is `true`. When `experimental-backends` is `false`, and the `--experimental-backends` option is *not* given, everything looks/works as expected.

**Comment by ibhagwan** [comment]
I rebased the code on the latest from the main branch, can you guys try using the latest code from [next-rebase](https://github.com/ibhagwan/picom/tree/next-rebase)?

**Comment by BachoSeven** [comment]
@ibhagwan will try it out! Are there any specific things to look out for that could be broken in the rebase?

**Comment by ibhagwan** [comment]
> @ibhagwan will try it out! Are there any specific things to look out for that could be broken in the rebase?

I've tested it locally and it behaves identically to the old fork with the different configuration options, that being said, the rebase was complex with many conflicts as it's been a while since I updated the code, in addition, the code added by the maintainers was slightly different than mine so I had to tread carefully so anything can be broken :-)

**Comment by kdkasad** [comment]
> I rebased the code on the latest from the main branch, can you guys try using the latest code from [next-rebase](https://github.com/ibhagwan/picom/tree/next-rebase)?

Doesn't seem to fix any of the problems relating to rounded corners. Here are some screenshots:

**`experimental-backends` set to `true`:**
![image](https://user-images.githubusercontent.com/63574107/107105172-cbd17c80-67d9-11eb-8d2d-5e9a8532c697.png)

**`experimental-backends` set to `false`:**
![image](https://user-images.githubusercontent.com/63574107/107105198-e9064b00-67d9-11eb-95a9-95a5fb53cc43.png)

These are exactly the same artifacts that appear with the `next` branch.

I'll continue to use the `next-rebase` branch for a while to see if I find any problems.

**Comment by ibhagwan** [comment]
> > I rebased the code on the latest from the main branch, can you guys try using the latest code from [next-rebase](https://github.com/ibhagwan/picom/tree/next-rebase)?
> 
> Doesn't seem to fix any of the problems relating to rounded corners. Here are some screenshots:
> 
> **`experimental-backends` set to `true`:**
> ![image](https://user-images.githubusercontent.com/63574107/107105172-cbd17c80-67d9-11eb-8d2d-5e9a8532c697.png)
> 
> **`experimental-backends` set to `false`:**
> ![image](https://user-images.githubusercontent.com/63574107/107105198-e9064b00-67d9-11eb-95a9-95a5fb53cc43.png)
> 
> These are exactly the same artifacts that appear with the `next` branch.
> 
> I'll continue to use the `next-rebase` branch for a while to see if I find any problems.

Thanks @kdkasad!

I'm not sure if the image is zoomed or your border width really big? What is your border thickness? Are you using any border rules or the automatic border detection? what happens when you disable shadows?

**Comment by kdkasad** [comment]
> > > I rebased the code on the latest from the main branch, can you guys try using the latest code from [next-rebase](https://github.com/ibhagwan/picom/tree/next-rebase)?
> > 
> > 
> > Doesn't seem to fix any of the problems relating to rounded corners. Here are some screenshots:
> > **`experimental-backends` set to `true`:**
> > ![image](https://user-images.githubusercontent.com/63574107/107105172-cbd17c80-67d9-11eb-8d2d-5e9a8532c697.png)
> > **`experimental-backends` set to `false`:**
> > ![image](https://user-images.githubusercontent.com/63574107/107105198-e9064b00-67d9-11eb-95a9-95a5fb53cc43.png)
> > These are exactly the same artifacts that appear with the `next` branch.
> > I'll continue to use the `next-rebase` branch for a while to see if I find any problems.
> 
> Thanks @kdkasad!
> 
> I'm not sure if the image is zoomed or your border width really big? What is your border thickness? Are you using any border rules or the automatic border detection? what happens when you disable shadows?

Sorry, I thought we were talking about just rounded corners, not borders. I can try with borders, though. I won't get to that for a few hours at least.

**Comment by ibhagwan** [comment]
> > > > I rebased the code on the latest from the main branch, can you guys try using the latest code from [next-rebase](https://github.com/ibhagwan/picom/tree/next-rebase)?
> > > 
> > > 
> > > Doesn't seem to fix any of the problems relating to rounded corners. Here are some screenshots:
> > > **`experimental-backends` set to `true`:**
> > > ![image](https://user-images.githubusercontent.com/63574107/107105172-cbd17c80-67d9-11eb-8d2d-5e9a8532c697.png)
> > > **`experimental-backends` set to `false`:**
> > > ![image](https://user-images.githubusercontent.com/63574107/107105198-e9064b00-67d9-11eb-95a9-95a5fb53cc43.png)
> > > These are exactly the same artifacts that appear with the `next` branch.
> > > I'll continue to use the `next-rebase` branch for a while to see if I find any problems.
> > 
> > 
> > Thanks @kdkasad!
> > I'm not sure if the image is zoomed or your border width really big? What is your border thickness? Are you using any border rules or the automatic border detection? what happens when you disable shadows?
> 
> Sorry, I thought we were talking about just rounded corners, not borders. I can try with borders, though. I won't get to that for a few hours at least.
> 
> However it also has this weird artifact with rounded corners + shadows.

Sorry I misunderstood what was the issue you're referring to, since the title of this issue is "rounded borders do not work" I thought you had an issue with the internal part of the border not being rounded without `experimental-backends`.

Unfortunately ATM I have no plans to fix the shadows with rounded corners.

**Comment by ibhagwan** [comment]
I guess I can close this issue for now as it has diverged from the original topic, feel free to reopen.
